---
# Create a playbook that creates a folder in the current directory, and copies a random file to the newly created folder.
# The user of the directory must be root and only this root user can have write/read/execute permissions on the file created (others will have no access at all).

# Run this playbook with: ansible-playbook --ask-become-pass exercise-1-dirs-root.yml -v

- hosts: localhost
  tasks:
    - name: check whoami
      shell: whoami

    - name: Create a folder in the current directory
      file:
        path: "./foo-aw"
        state: directory

    # File /tmp/bar-aw must exist
    - name: Copy /tmp/bar-aw to ./foo-aw
      copy:
        src: "/tmp/bar-aw"
        dest: "./foo-aw"
        owner: "root"
        mode: 0700
      become: true
      become_user: "root"
      become_method: "sudo"
