---
# Create a playbook that performs the following tasks:
# - create a /tmp/test-loops-source and /tmp/test-loops-target directories
# - creates 2 files on /tmp/test-loops-source
# - copy the 2 different files to /tmp/test-loops-target
# - for one of the files on /tmp/test-loops-source, rename the file to “file1-readable” only if the file is readable

# Run it with: ansible-playbook exercise-4-loops-when.yml -v
- hosts: all
  vars:
    source_dir: /tmp/test-loops-source
    target_dir: /tmp/test-loops-target
    suffix: "-readable"
  tasks:
    - name: Create directory
      file: path={{ item }} state=directory
      with_items:
        - "{{ source_dir }}"
        - "{{ target_dir }}"

    - name: Create files
      file:
        path: "{{ source_dir }}/{{ item }}"
        state: touch
      with_items:
        - file1
        - file2

    - name: Copy files to directory
      copy:
        src: "{{ source_dir }}/{{ item }}"
        dest: "{{ target_dir }}"
      with_items:
        - file1
        - file2

    - name: Get stats for file1
      stat: path="{{ source_dir }}/file1"
      register: file1_stat

    - name: Rename file1 to file1-exec if readable
      command: mv {{ source_dir }}/file1 {{ source_dir }}/file1{{ suffix }}
      when: file1_stat.stat.readable
